### ISSUE TITLE
upload failure

### ISSUE THREAD

**Issue by meeech** [meeech/Shopify-Theme-Tool#27]
[Information] {"event":"create","base":"/Users/mitch/src/solli.amihod.com/meeech-32676676","relative":"assets/jquery-min.js"}
{"event":"create","base":"/Users/mitch/src/solli.amihod.com/meeech-32676676","relative":"assets/jquery.ba-throttle-debounce.min.js"}

[00:14:03:023] [Ti.Network.TCPSocket] [Error] Failed to fire event: target=Network.TCPSocket reason=(JavaScript.KKJSObject) { message : "Unable to parse JSON string", line : 141d, sourceId : 1.79531e+08d, sourceURL : "app://com.meeech.shopify_theme2/js/watchers.js", name : "SyntaxError"}

Seems to repro when you drag 2 new files in

**Comment by parkerault** [comment]
I've been getting this to the point that the app is almost unusable. I think it's related to the way that webpack is creating new files after compilation. It doesn't seem to happen if I open the compiled file and manually save it, so maybe it's a problem with replacing an existing file instead of saving it.

Edit: I missed the last sentence in your description. Yes, this is exactly what is happening. Webpack is compiling several files at once, which causes the error.

**Comment by meeech** [comment]
@parkerault sorry you having issues still. I'd suggest looking at the new tool shopify recently released to work with themes. it should be more compat with using webpack workflow

**Comment by parkerault** [comment]
Awesome, I didn't know they had released a new tool. Thanks!

If anyone stumbles upon this via google, the shopify_theme gem is here: http://shopify.github.io/shopify_theme/

**Comment by meeech** [comment]
@parkerault It's actually http://themekit.cat/

the shopify_theme gem also seems dropped
